/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Updated;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computers
 */
public class LibrarianPage extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianPage2
     */
    int xMouse ;
    int yMouse ;
   
    
    public LibrarianPage() {

        initComponents();

        welcomePanel.setVisible(true);
        tabbedPane.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        viewBooksbtn = new javax.swing.JToggleButton();
        issueBooksbtn = new javax.swing.JToggleButton();
        viewIssuedBooksbtn = new javax.swing.JToggleButton();
        addBookbtn = new javax.swing.JToggleButton();
        signOutbtn = new javax.swing.JButton();
        display = new javax.swing.JPanel();
        minimizebtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        addBookPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addBookbtn2 = new javax.swing.JButton();
        titleField = new javax.swing.JTextField();
        categoryField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        autherField = new javax.swing.JTextField();
        viewBooksPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBookbtn = new javax.swing.JButton();
        deleteBookField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        issueBookPanel = new javax.swing.JPanel();
        issueNameField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        issueAddressField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        issuePhoneNumberField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        issueEmailField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        issueBookbtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        issueIDField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        issueTitleField = new javax.swing.JTextField();
        reservationDateField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        viewIssuedBooksPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        returnBookField = new javax.swing.JTextField();
        retunBookbtn = new javax.swing.JButton();
        returnBookField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        welcomePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(21, 25, 28));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewBooksbtn.setBackground(new java.awt.Color(21, 25, 28));
        buttonGroup1.add(viewBooksbtn);
        viewBooksbtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        viewBooksbtn.setForeground(new java.awt.Color(169, 224, 49));
        viewBooksbtn.setText("View Books");
        viewBooksbtn.setBorder(null);
        viewBooksbtn.setBorderPainted(false);
        viewBooksbtn.setFocusPainted(false);
        viewBooksbtn.setFocusable(false);
        viewBooksbtn.setOpaque(false);
        viewBooksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksbtnActionPerformed(evt);
            }
        });
        sidebar.add(viewBooksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 170, 50));

        issueBooksbtn.setBackground(new java.awt.Color(21, 25, 28));
        buttonGroup1.add(issueBooksbtn);
        issueBooksbtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        issueBooksbtn.setForeground(new java.awt.Color(169, 224, 49));
        issueBooksbtn.setText("Issue Book");
        issueBooksbtn.setBorder(null);
        issueBooksbtn.setBorderPainted(false);
        issueBooksbtn.setFocusPainted(false);
        issueBooksbtn.setFocusable(false);
        issueBooksbtn.setOpaque(false);
        issueBooksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBooksbtnActionPerformed(evt);
            }
        });
        sidebar.add(issueBooksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 170, 50));

        viewIssuedBooksbtn.setBackground(new java.awt.Color(21, 25, 28));
        buttonGroup1.add(viewIssuedBooksbtn);
        viewIssuedBooksbtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        viewIssuedBooksbtn.setForeground(new java.awt.Color(169, 224, 49));
        viewIssuedBooksbtn.setText("View Issued Books");
        viewIssuedBooksbtn.setBorder(null);
        viewIssuedBooksbtn.setBorderPainted(false);
        viewIssuedBooksbtn.setFocusPainted(false);
        viewIssuedBooksbtn.setFocusable(false);
        viewIssuedBooksbtn.setOpaque(false);
        viewIssuedBooksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewIssuedBooksbtnActionPerformed(evt);
            }
        });
        sidebar.add(viewIssuedBooksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 170, 50));

        addBookbtn.setBackground(new java.awt.Color(21, 25, 28));
        buttonGroup1.add(addBookbtn);
        addBookbtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        addBookbtn.setForeground(new java.awt.Color(169, 224, 49));
        addBookbtn.setText("Add Book");
        addBookbtn.setBorder(null);
        addBookbtn.setBorderPainted(false);
        addBookbtn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        addBookbtn.setFocusPainted(false);
        addBookbtn.setFocusable(false);
        addBookbtn.setOpaque(false);
        addBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookbtnActionPerformed(evt);
            }
        });
        sidebar.add(addBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 170, 50));

        signOutbtn.setBackground(new java.awt.Color(187, 187, 187));
        signOutbtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        signOutbtn.setForeground(new java.awt.Color(169, 224, 49));
        signOutbtn.setText("Sign out");
        signOutbtn.setBorder(null);
        signOutbtn.setBorderPainted(false);
        signOutbtn.setContentAreaFilled(false);
        signOutbtn.setFocusPainted(false);
        signOutbtn.setFocusable(false);
        signOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutbtnActionPerformed(evt);
            }
        });
        sidebar.add(signOutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 70, 30));

        jPanel1.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 540));

        display.setBackground(new java.awt.Color(31, 36, 42));
        display.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        minimizebtn.setToolTipText("Minimize");
        minimizebtn.setBorder(null);
        minimizebtn.setBorderPainted(false);
        minimizebtn.setContentAreaFilled(false);
        minimizebtn.setFocusPainted(false);
        minimizebtn.setRequestFocusEnabled(false);
        minimizebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        minimizebtn.setVerifyInputWhenFocusTarget(false);
        minimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebtnMouseClicked(evt);
            }
        });
        minimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizebtnActionPerformed(evt);
            }
        });
        display.add(minimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 40, 40));

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        closebtn.setToolTipText("Close");
        closebtn.setBorder(null);
        closebtn.setBorderPainted(false);
        closebtn.setContentAreaFilled(false);
        closebtn.setRequestFocusEnabled(false);
        closebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        closebtn.setVerifyInputWhenFocusTarget(false);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        display.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 40, 40));

        tabbedPane.setFocusable(false);

        addBookPanel.setBackground(new java.awt.Color(31, 36, 42));
        addBookPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                addBookPanelMouseDragged(evt);
            }
        });
        addBookPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addBookPanelMousePressed(evt);
            }
        });
        addBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("ID");
        addBookPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 40, -1));

        jLabel2.setBackground(new java.awt.Color(187, 187, 187));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Title");
        addBookPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel3.setBackground(new java.awt.Color(187, 187, 187));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("Category");
        addBookPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(187, 187, 187));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("Auther");
        addBookPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        addBookbtn2.setBackground(new java.awt.Color(169, 224, 70));
        addBookbtn2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        addBookbtn2.setForeground(new java.awt.Color(21, 25, 28));
        addBookbtn2.setText("Add Book");
        addBookbtn2.setBorder(null);
        addBookbtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBookbtn2.setFocusPainted(false);
        addBookbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookbtn2ActionPerformed(evt);
            }
        });
        addBookPanel.add(addBookbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 180, 30));

        titleField.setBackground(new java.awt.Color(31, 36, 42));
        titleField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        titleField.setForeground(new java.awt.Color(169, 224, 49));
        titleField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        titleField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                titleFieldMouseMoved(evt);
            }
        });
        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });
        addBookPanel.add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 160, 30));

        categoryField.setBackground(new java.awt.Color(31, 36, 42));
        categoryField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        categoryField.setForeground(new java.awt.Color(169, 224, 49));
        categoryField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        categoryField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                categoryFieldMouseMoved(evt);
            }
        });
        addBookPanel.add(categoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, 30));

        idField.setBackground(new java.awt.Color(31, 36, 42));
        idField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        idField.setForeground(new java.awt.Color(169, 224, 49));
        idField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        idField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                idFieldMouseMoved(evt);
            }
        });
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        addBookPanel.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 160, 30));

        autherField.setBackground(new java.awt.Color(31, 36, 42));
        autherField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        autherField.setForeground(new java.awt.Color(169, 224, 49));
        autherField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        autherField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                autherFieldMouseMoved(evt);
            }
        });
        addBookPanel.add(autherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 160, 30));

        tabbedPane.addTab("tab1", addBookPanel);

        viewBooksPanel.setBackground(new java.awt.Color(31, 36, 42));
        viewBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(31, 36, 42));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Auther", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        viewBooksPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 560, 220));

        deleteBookbtn.setBackground(new java.awt.Color(169, 224, 49));
        deleteBookbtn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        deleteBookbtn.setForeground(new java.awt.Color(21, 25, 28));
        deleteBookbtn.setText("Delete Book");
        deleteBookbtn.setBorder(null);
        deleteBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBookbtn.setFocusPainted(false);
        deleteBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookbtnActionPerformed(evt);
            }
        });
        viewBooksPanel.add(deleteBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 110, 30));

        deleteBookField.setBackground(new java.awt.Color(31, 36, 42));
        deleteBookField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        deleteBookField.setForeground(new java.awt.Color(169, 224, 49));
        deleteBookField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        deleteBookField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteBookFieldMouseMoved(evt);
            }
        });
        deleteBookField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookFieldActionPerformed(evt);
            }
        });
        viewBooksPanel.add(deleteBookField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, 30));

        jLabel5.setBackground(new java.awt.Color(187, 187, 187));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("Enter ID of Book To delete");
        viewBooksPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 200, 30));

        tabbedPane.addTab("tab2", viewBooksPanel);

        issueBookPanel.setBackground(new java.awt.Color(31, 36, 42));
        issueBookPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueNameField.setBackground(new java.awt.Color(31, 36, 42));
        issueNameField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issueNameField.setForeground(new java.awt.Color(169, 224, 49));
        issueNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        issueNameField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                issueNameFieldMouseMoved(evt);
            }
        });
        issueNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueNameFieldActionPerformed(evt);
            }
        });
        issueBookPanel.add(issueNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, 40));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setText("Name");
        issueBookPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 20));

        issueAddressField.setBackground(new java.awt.Color(31, 36, 42));
        issueAddressField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issueAddressField.setForeground(new java.awt.Color(169, 224, 49));
        issueAddressField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        issueAddressField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                issueAddressFieldMouseMoved(evt);
            }
        });
        issueBookPanel.add(issueAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 40));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel16.setText("Address");
        issueBookPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 60, 20));

        issuePhoneNumberField.setBackground(new java.awt.Color(31, 36, 42));
        issuePhoneNumberField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issuePhoneNumberField.setForeground(new java.awt.Color(169, 224, 49));
        issuePhoneNumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        issuePhoneNumberField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                issuePhoneNumberFieldMouseMoved(evt);
            }
        });
        issueBookPanel.add(issuePhoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 160, 40));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(169, 224, 49));
        jLabel17.setText("Phone Number");
        issueBookPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, -1));

        issueEmailField.setBackground(new java.awt.Color(31, 36, 42));
        issueEmailField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issueEmailField.setForeground(new java.awt.Color(169, 224, 49));
        issueEmailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        issueEmailField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                issueEmailFieldMouseMoved(evt);
            }
        });
        issueBookPanel.add(issueEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 40));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(169, 224, 49));
        jLabel18.setText("Email");
        issueBookPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 60, 20));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(169, 224, 49));
        jLabel20.setText("Book Info.");
        issueBookPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 120, 30));

        issueBookbtn.setBackground(new java.awt.Color(169, 224, 49));
        issueBookbtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issueBookbtn.setForeground(new java.awt.Color(21, 25, 28));
        issueBookbtn.setText("Issue Book");
        issueBookbtn.setBorder(null);
        issueBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueBookbtn.setFocusPainted(false);
        issueBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookbtnActionPerformed(evt);
            }
        });
        issueBookPanel.add(issueBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 220, 30));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(169, 224, 49));
        jLabel21.setText("Borrower Info.");
        issueBookPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 30));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(169, 224, 49));
        jLabel22.setText("ID");
        issueBookPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 20, 20));

        issueIDField.setBackground(new java.awt.Color(31, 36, 42));
        issueIDField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issueIDField.setForeground(new java.awt.Color(169, 224, 49));
        issueIDField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        issueIDField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                issueIDFieldMouseMoved(evt);
            }
        });
        issueIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueIDFieldActionPerformed(evt);
            }
        });
        issueBookPanel.add(issueIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 160, 40));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(169, 224, 49));
        jLabel23.setText("Title");
        issueBookPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 60, 20));

        issueTitleField.setBackground(new java.awt.Color(31, 36, 42));
        issueTitleField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        issueTitleField.setForeground(new java.awt.Color(169, 224, 49));
        issueTitleField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        issueTitleField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                issueTitleFieldMouseMoved(evt);
            }
        });
        issueBookPanel.add(issueTitleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 160, 40));

        reservationDateField.setBackground(new java.awt.Color(31, 36, 42));
        reservationDateField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        reservationDateField.setForeground(new java.awt.Color(169, 224, 49));
        reservationDateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        reservationDateField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reservationDateFieldMouseMoved(evt);
            }
        });
        issueBookPanel.add(reservationDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 160, 40));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(169, 224, 49));
        jLabel24.setText("Reservation Date");
        issueBookPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 160, 20));

        tabbedPane.addTab("tab3", issueBookPanel);

        viewIssuedBooksPanel.setBackground(new java.awt.Color(31, 36, 42));
        viewIssuedBooksPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(31, 36, 42));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Title", "Borrower Name", "Email", "Address", "Phone ", "Reserve Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        viewIssuedBooksPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 560, 220));

        jLabel7.setBackground(new java.awt.Color(187, 187, 187));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("Return a Book");
        viewIssuedBooksPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 130, 30));

        returnBookField.setBackground(new java.awt.Color(31, 36, 42));
        returnBookField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        returnBookField.setForeground(new java.awt.Color(169, 224, 49));
        returnBookField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        returnBookField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                returnBookFieldMouseMoved(evt);
            }
        });
        returnBookField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookFieldActionPerformed(evt);
            }
        });
        viewIssuedBooksPanel.add(returnBookField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 220, 30));

        retunBookbtn.setBackground(new java.awt.Color(169, 224, 49));
        retunBookbtn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        retunBookbtn.setForeground(new java.awt.Color(21, 25, 28));
        retunBookbtn.setText("Return Book");
        retunBookbtn.setBorder(null);
        retunBookbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retunBookbtn.setFocusPainted(false);
        retunBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retunBookbtnActionPerformed(evt);
            }
        });
        viewIssuedBooksPanel.add(retunBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 110, 30));

        returnBookField1.setBackground(new java.awt.Color(31, 36, 42));
        returnBookField1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        returnBookField1.setForeground(new java.awt.Color(169, 224, 49));
        returnBookField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        returnBookField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                returnBookField1MouseMoved(evt);
            }
        });
        returnBookField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookField1ActionPerformed(evt);
            }
        });
        viewIssuedBooksPanel.add(returnBookField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 220, 30));

        jLabel8.setBackground(new java.awt.Color(187, 187, 187));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setText("Returning Date");
        viewIssuedBooksPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 220, 30));

        jLabel9.setBackground(new java.awt.Color(187, 187, 187));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(169, 224, 49));
        jLabel9.setText("Book ID");
        viewIssuedBooksPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 220, 30));

        tabbedPane.addTab("tab4", viewIssuedBooksPanel);

        display.add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -25, 720, 530));

        welcomePanel.setBackground(new java.awt.Color(31, 36, 42));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 70));
        jLabel6.setText("Welcome To Librarian Page");
        welcomePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 330, 150));

        display.add(welcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 760, 480));

        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 720, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        setSize(new java.awt.Dimension(713, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutbtnActionPerformed
        LoginFrame logFrame = new LoginFrame();
        logFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signOutbtnActionPerformed

    private void addBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookbtnActionPerformed

        welcomePanel.setVisible(false);
        tabbedPane.setVisible(true);
        tabbedPane.setSelectedIndex(0);


    }//GEN-LAST:event_addBookbtnActionPerformed

    private void viewIssuedBooksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIssuedBooksbtnActionPerformed

        welcomePanel.setVisible(false);
        tabbedPane.setVisible(true);
        tabbedPane.setSelectedIndex(3);

        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/myDataBase", "root", "12345");
            Statement st = con.createStatement();
            String sql = "select * from IssuedBooks"; //Retreive data from database
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();
            tblModel.setRowCount(0);

            while (rs.next()) {     //data will be added until finish
                //String id=String.valueOf(rs.getInt("id"));
                String id = rs.getString("Book_ID"); //id is a colum name  
                String title = rs.getString("Book_Title");
                String borrowerName = rs.getString("Borrower_Name");
                String email = rs.getString("Email");
                String address = rs.getString("Address");
                String phoneNumber = rs.getString("Phone_Number");
                String ResDate = rs.getString("ReservationDate");
                
                // string array for store data into jtable
                String tbData[] = {id, title, borrowerName, email,address ,phoneNumber,ResDate};

                //add string array data into jtable
                tblModel.addRow(tbData);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_viewIssuedBooksbtnActionPerformed

    private void viewBooksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksbtnActionPerformed

        welcomePanel.setVisible(false);
        tabbedPane.setVisible(true);
        tabbedPane.setSelectedIndex(1);

        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/myDataBase", "root", "12345");
            Statement st = con.createStatement();
            String sql = "select * from Books"; //Retreive data from database
            ResultSet rs = st.executeQuery(sql);   
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.setRowCount(0);

            while (rs.next()) {     //data will be added until finish
                //String id=String.valueOf(rs.getInt("id"));
                String id = rs.getString("ID"); //id is a colum name  
                String title = rs.getString("Title");
                String auther = rs.getString("Auther");
                String category = rs.getString("Category");

                // string array for store data into jtable
                String tbData[] = {id, title, auther, category};

                //add string array data into jtable
                tblModel.addRow(tbData);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_viewBooksbtnActionPerformed

    private void addBookbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookbtn2ActionPerformed

        try {

            String id = idField.getText().trim();
            idField.setText(null);
            // int m_int = Integer.parseInt(m);

            String title = titleField.getText().trim();
            titleField.setText(null);

            String auther = autherField.getText().trim();
            autherField.setText(null);

            String category = categoryField.getText().trim();
            categoryField.setText(null);

            //int quan_int = Integer.parseInt(quan);
            if ((id.isEmpty() || title.isEmpty() || auther.isEmpty() || category.isEmpty())) {
                JOptionPane.showMessageDialog(this, "Book Addition Failed", "Please Fill in all Fields", JOptionPane.ERROR_MESSAGE);
            }

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/myDataBase", "root", "12345");

            String query = "INSERT INTO Books values('" + id + "','" + title + "','" + auther + "','"
                    + category + "')";

            Statement st = con.createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "The Book is Added Successfully");

        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_addBookbtn2ActionPerformed

    private void deleteBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookbtnActionPerformed

     
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/mydataBase", "root", "12345");
            Statement st = con.createStatement();
            st.executeUpdate("Delete FROM Books WHERE ID='"+ deleteBookField.getText() + "'");
  
            JOptionPane.showMessageDialog(this, "Book is Deleted Succseefully") ;
            
        } 
        catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_deleteBookbtnActionPerformed

    private void issueNameFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueNameFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_issueNameFieldMouseMoved

    private void issueNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueNameFieldActionPerformed

    private void issueAddressFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueAddressFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_issueAddressFieldMouseMoved

    private void issuePhoneNumberFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuePhoneNumberFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_issuePhoneNumberFieldMouseMoved

    private void issueEmailFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueEmailFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_issueEmailFieldMouseMoved

    private void issueBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookbtnActionPerformed

       // welcomePanel.setVisible(false);
       // tabbedPane.setVisible(true);

        String name = issueNameField.getText();
        String email = issueEmailField.getText();
        String address = issueAddressField.getText();
        String mobileNumber = issuePhoneNumberField.getText();

        String BookID = issueIDField.getText();
        String BookTitle = issueTitleField.getText();
        String ResDate = reservationDateField.getText() ;

        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/mydataBase", "root", "12345");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select *from Books where Books.Title='" + BookTitle + "'");

            if (rs.next()) {

                String query = "INSERT INTO IssuedBooks values('" + BookID + "','"
                        + BookTitle + "','" + name + "','" + email + "','"
                        + address + "','" + mobileNumber + "','" + ResDate + "')";

                st.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "[" + BookTitle + "]" + " is Issued Succesfuly");
                issueNameField.setText(null);
                issueAddressField.setText(null);
                issueEmailField.setText(null );
                issuePhoneNumberField.setText(null);
                issueIDField.setText(null);
                issueTitleField.setText(null);
                reservationDateField.setText(null) ;

            } else {
                JOptionPane.showMessageDialog(this, "[" + BookTitle + "]" + " Does not Exist");
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_issueBookbtnActionPerformed

    private void issueIDFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueIDFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_issueIDFieldMouseMoved

    private void issueIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueIDFieldActionPerformed

    private void issueTitleFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueTitleFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_issueTitleFieldMouseMoved

    private void issueBooksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBooksbtnActionPerformed

        welcomePanel.setVisible(false);
        tabbedPane.setVisible(true);
        tabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_issueBooksbtnActionPerformed

    private void titleFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldMouseMoved

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void categoryFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryFieldMouseMoved

    private void idFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldMouseMoved

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void autherFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autherFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_autherFieldMouseMoved

    private void deleteBookFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBookFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBookFieldMouseMoved

    private void deleteBookFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBookFieldActionPerformed

    private void returnBookFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBookFieldMouseMoved

    private void returnBookFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBookFieldActionPerformed

    private void retunBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retunBookbtnActionPerformed
        
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/mydataBase", "root", "12345");
            Statement st = con.createStatement();
            st.executeUpdate("Delete FROM IssuedBooks WHERE Book_ID='"+ returnBookField.getText() + "'");
  
            JOptionPane.showMessageDialog(this, "Book is Returned Succseefully") ;
            
        } 
        catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_retunBookbtnActionPerformed

    private void addBookPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookPanelMouseDragged

    }//GEN-LAST:event_addBookPanelMouseDragged

    private void addBookPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookPanelMousePressed

    }//GEN-LAST:event_addBookPanelMousePressed

    private void minimizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizebtnMouseClicked

    private void minimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizebtnActionPerformed

    }//GEN-LAST:event_minimizebtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
       xMouse = evt.getX() ;
       yMouse = evt.getY() ;
    }//GEN-LAST:event_jPanel1MousePressed

    private void reservationDateFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationDateFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationDateFieldMouseMoved

    private void returnBookField1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookField1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBookField1MouseMoved

    private void returnBookField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBookField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel addBookPanel;
    public javax.swing.JToggleButton addBookbtn;
    public javax.swing.JButton addBookbtn2;
    public javax.swing.JTextField autherField;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField categoryField;
    public javax.swing.JButton closebtn;
    public javax.swing.JTextField deleteBookField;
    public javax.swing.JButton deleteBookbtn;
    public javax.swing.JPanel display;
    public javax.swing.JTextField idField;
    public javax.swing.JTextField issueAddressField;
    public javax.swing.JPanel issueBookPanel;
    public javax.swing.JButton issueBookbtn;
    public javax.swing.JToggleButton issueBooksbtn;
    public javax.swing.JTextField issueEmailField;
    public javax.swing.JTextField issueIDField;
    public javax.swing.JTextField issueNameField;
    public javax.swing.JTextField issuePhoneNumberField;
    public javax.swing.JTextField issueTitleField;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JButton minimizebtn;
    public javax.swing.JTextField reservationDateField;
    public javax.swing.JButton retunBookbtn;
    public javax.swing.JTextField returnBookField;
    public javax.swing.JTextField returnBookField1;
    public javax.swing.JPanel sidebar;
    public javax.swing.JButton signOutbtn;
    public javax.swing.JTabbedPane tabbedPane;
    public javax.swing.JTextField titleField;
    public javax.swing.JPanel viewBooksPanel;
    public javax.swing.JToggleButton viewBooksbtn;
    public javax.swing.JPanel viewIssuedBooksPanel;
    public javax.swing.JToggleButton viewIssuedBooksbtn;
    public javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
