/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Updated;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Computers
 */
public class RegisterationFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterationFrame
     */
    int xMouse ;
    int yMouse ;
    
    public RegisterationFrame() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        lastnameField = new javax.swing.JTextField();
        phonenumberField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        backToLogin = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.setBackground(new java.awt.Color(31, 36, 42));
        usernameField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        usernameField.setForeground(new java.awt.Color(169, 224, 49));
        usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        usernameField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                usernameFieldMouseMoved(evt);
            }
        });
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel6.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, 40));

        lastnameField.setBackground(new java.awt.Color(31, 36, 42));
        lastnameField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lastnameField.setForeground(new java.awt.Color(169, 224, 49));
        lastnameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        lastnameField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lastnameFieldMouseMoved(evt);
            }
        });
        jPanel6.add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, 40));

        phonenumberField.setBackground(new java.awt.Color(31, 36, 42));
        phonenumberField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        phonenumberField.setForeground(new java.awt.Color(169, 224, 49));
        phonenumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        phonenumberField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                phonenumberFieldMouseMoved(evt);
            }
        });
        jPanel6.add(phonenumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 330, 40));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(169, 224, 49));
        jLabel14.setText("Username");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 20));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(169, 224, 49));
        jLabel15.setText("Last Name");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 90, 20));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(169, 224, 49));
        jLabel18.setText("Password");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 314, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(169, 224, 49));
        jLabel17.setText("Phone Number");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 314, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel16.setText("Email");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 314, -1));

        backToLogin.setBackground(new java.awt.Color(169, 224, 49));
        backToLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        backToLogin.setForeground(new java.awt.Color(169, 224, 49));
        backToLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_25px.png"))); // NOI18N
        backToLogin.setText("Back to login");
        backToLogin.setBorder(null);
        backToLogin.setContentAreaFilled(false);
        backToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToLogin.setRequestFocusEnabled(false);
        backToLogin.setVerifyInputWhenFocusTarget(false);
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });
        jPanel6.add(backToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 150, -1));

        signUpButton.setBackground(new java.awt.Color(169, 224, 49));
        signUpButton.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(21, 25, 28));
        signUpButton.setText("Sign up");
        signUpButton.setBorder(null);
        signUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpButton.setFocusPainted(false);
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel6.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 330, 40));

        emailField.setBackground(new java.awt.Color(31, 36, 42));
        emailField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(169, 224, 49));
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        emailField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                emailFieldMouseMoved(evt);
            }
        });
        jPanel6.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 330, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        firstnameField.setBackground(new java.awt.Color(31, 36, 42));
        firstnameField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        firstnameField.setForeground(new java.awt.Color(169, 224, 49));
        firstnameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        firstnameField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                firstnameFieldMouseMoved(evt);
            }
        });
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });
        jPanel6.add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, 40));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setText("First Name");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 20));

        regPasswordField.setBackground(new java.awt.Color(31, 36, 42));
        regPasswordField.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        regPasswordField.setForeground(new java.awt.Color(169, 224, 49));
        regPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        regPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPasswordFieldActionPerformed(evt);
            }
        });
        jPanel6.add(regPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 330, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(456, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed

                String firstName = firstnameField.getText();
                String lastName = lastnameField.getText();
                String emailId = emailField.getText();
                String userName = usernameField.getText();
                String mobileNumber = phonenumberField.getText();
                String password = regPasswordField.getText();

                String msg = "" + firstName;
                msg += " \n";
                
                try {
                    Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/myDataBase", "root", "12345");

                    String query = "INSERT INTO myTable values('" + firstName + "','" + lastName + "','" + userName + "','" +
                        password + "','" + emailId + "','" + mobileNumber + "')";

                    Statement sta = connection.createStatement();
                    int x = sta.executeUpdate(query);
                    if (x == 0) {
                        JOptionPane.showMessageDialog(signUpButton, "This already exists");
                    } else {
                        JOptionPane.showMessageDialog(signUpButton,
                            "Welcome, " + msg + "Your account is sucessfully created");
                        firstnameField.setText(null) ;
                        lastnameField.setText(null) ;
                        usernameField.setText(null) ;
                        emailField.setText(null) ;
                        regPasswordField.setText(null) ;
                        phonenumberField.setText(null) ;
                    }
                    connection.close();
                } 
                catch (Exception exception) {
                    exception.printStackTrace();
                }             
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
        LoginFrame logFrame = new LoginFrame() ;
        logFrame.setVisible(true) ;
        this.dispose() ;        
    }//GEN-LAST:event_backToLoginActionPerformed

    private void phonenumberFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonenumberFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberFieldMouseMoved

    private void lastnameFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastnameFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldMouseMoved

    private void usernameFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldMouseMoved

    private void emailFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldMouseMoved

    private void firstnameFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnameFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldMouseMoved

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen() ;
        int y = evt.getYOnScreen() ;
        
        this.setLocation(x - xMouse, y - yMouse) ;
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
       xMouse = evt.getX() ;
       yMouse = evt.getY() ;
    }//GEN-LAST:event_jPanel3MousePressed

    private void regPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToLogin;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JTextField phonenumberField;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
